### ISSUE TITLE
Is the mapper function enabled?

### ISSUE THREAD

**Issue by chriswillis** [paultpearson/TDAmapper#1]
Working through some of your examples. Functions mapper1D and 2D work but a call like this:

    m4 <- mapper(dist(X), f[,1], 5, 50, 5)

results in an error 

    Error: could not find function "mapper"

Thanks for your efforts,

// chris

**Comment by paultpearson** [comment]
Hi Chris,

The `mapper()` function is still undergoing testing.  The `mapper()` function is available if you install TDAmapper from the github repository, but it is not available yet from the package on CRAN.  The `mapper1D()` and `mapper2D()` functions are available both from CRAN and the github repo.  I have updated the documentation to note this discrepancy.  Please let me know if you have any problems installing the TDAmapper package from github or getting `mapper()` to work.  I apologize for any confusion.

Best regards,

Paul Pearson

**Comment by chriswillis** [comment]
Thanks for the response. Really appreciate the work you are doing on this.
