### ISSUE TITLE
Set filter function

### ISSUE THREAD

**Issue by dpanagop** [paultpearson/TDAmapper#2]
Can you please give more details on the filter function. How can someone define a custom filter function?

Thank you.

**Comment by paultpearson** [comment]
This is not an issue with the code, so it should not have been submitted as an issue on github.

Example 1 has data consisting of 100 points in the plane with x=2*cos(0.5*(1:100)) and y=sin(1:100).  The filter function is a custom filter function given by projection onto the first coordinate: f(x,y) = x.  Thus, the 100 filter function values are 2*cos(0.5*(1:100)).
